### ISSUE TITLE
npm install doesn't work.

### ISSUE THREAD

**Issue by justinzw** [MistyCommunity/Documentation#20] opened 2019-02-05 20:26 UTC
when running` npm install` on the root directory I run into issues.
```
npm ERR! Cannot read property '0' of undefined
npm ERR! A complete log of this run can be found in:
```

**Comment by justinzw** [comment] 2019-02-06 13:27
might be something to do with this. But I'm not sure

npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but npm-shrinkwrap.json was generated for lockfileVersion@0. I'll try to do my best with it!
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but npm-shrinkwrap.json was generated for lockfileVersion@0. I'll try to do my best with it!

**Comment by justinzw** [comment] 2019-02-06 13:30
npm -v
6.4.1
node -v
v10.15.1

**Comment by justinzw** [comment] 2019-02-06 13:30
@johnathanDOS are you or Ben able to get `npm install` working?

**Comment by slivingston** [comment] 2019-02-07 02:28
@justinzw I am able to reproduce the error. I am searching for a solution now.

**Comment by slivingston** [comment] 2019-02-07 02:29
for reference, I have NPM v6.4.1, Node.js v10.15.0, all on Fedora 29

**Comment by slivingston** [comment] 2019-02-07 02:34
I tried to delete the directory `node_modules` and, thus, to get dependencies from upstream, but it fails because one of them is from a repo that does not exist: https://github.com/MistyCommunity/Documentation/blob/24ae35cca44fe0999199be4e5c4a50aa805b19c7/package.json#L52

**Comment by slivingston** [comment] 2019-02-07 02:36
(or the repo might be secret)

**Comment by slivingston** [comment] 2019-02-07 02:37
@johnathanDOS is it necessary to use `git://github.com/brycekahle/metalsmith-register-helpers` instead of [the package with the same name on NPM](https://www.npmjs.com/package/metalsmith-register-helpers) ?

**Comment by johnathanDOS** [comment] 2019-02-07 05:03
@slivingston maybe not. I tried deleting `node_modules` and installing the dependencies from upstream after changing this: https://github.com/MistyCommunity/Documentation/blob/24ae35cca44fe0999199be4e5c4a50aa805b19c7/package.json#L52 to this: `"metalsmith-register-helpers": "0.4.0"` (the current version of that package on NPM). 

When I do this, I still see what @justinzw mentioned [here](https://github.com/MistyCommunity/Documentation/issues/20#issuecomment-461022549), but I no longer see [this error](https://github.com/MistyCommunity/Documentation/issues/20#issue-406960154). I'll need to look into this a bit more...

**Comment by slivingston** [comment] 2019-02-09 04:27
I also changed `metalsmith-register-partials` ([available on NPM](https://www.npmjs.com/package/metalsmith-register-partials)), and now I can build and view the Misty Docs successfully. Try the following patch:
```diff
diff --git a/package.json b/package.json
index 5d4681bb..02b951dd 100755
--- a/package.json
+++ b/package.json
@@ -49,8 +49,8 @@
     "metalsmith-paths": "2.1.1",
     "metalsmith-permalinks": "^0.4.0",
     "metalsmith-redirect": "^2.1.0",
-    "metalsmith-register-helpers": "git://github.com/brycekahle/metalsmith-register-helpers",
-    "metalsmith-register-partials": "git://github.com/spark/metalsmith-register-partials",
+    "metalsmith-register-helpers": "^0.4.0",
+    "metalsmith-register-partials": "^1.0.2",
     "metalsmith-serve": "0.0.7",
     "metalsmith-watch": "^1.0.1",
     "mocha": "^3.2.0",
```

**Comment by slivingston** [comment] 2019-02-09 04:33
the full sequence is:
1. clone repo, master branch (current tip: 5a55feedbcbf39d0f8955047b5d984c798a0eebd)
2. `rm -rf node_modules`
3. apply patch from [above](https://github.com/MistyCommunity/Documentation/issues/20#issuecomment-462012448) to package.json
4. `npm build` (actually, I prefer `yarn build`, but both work here)
5. `npm start` (or `yarn start`)
6. point Web browser at http://127.0.0.1:8080/

**Comment by johnathanDOS** [comment] 2019-02-20 00:03
Thanks @slivingston. I've updated those packages in package.json and it seems to have resolved the issue. I wonder if you and/or @justinzw would be willing to clone this repo (master branch) and try running `npm install`, then (if that's successful) `npm start`?

**Comment by slivingston** [comment] 2019-02-21 07:51
in a fresh Ubuntu 18.04 environment, I cloned this repo, and against the current tip of `master` branch (commit a3f8b906eba83b520ab496950f5adbb861c9ff69), `npm install` and `npm start` both succeed.

**Comment by johnathanDOS** [comment] 2019-02-21 17:26
Excellent! Much thanks to you both for calling this out troubleshooting solutions. 

I'm going to close this issue for now. If you notice other problems with package dependencies, please don't hesitate to open another issue 🙂

**Closed** 2019-02-21 17:27 UTC
